on: 
  push:
    branches:
      - main
name: Deploy
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-versions: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm run test
        run: |
          npm ci
          npm run test-headless
  deploy:
    runs-on: ubuntu-latest
    needs: test
    name: Deploying to surge
    steps:
      - uses: actions/checkout@v1
      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Test command line argument
        run: npm run command-line-arg -- --test_secret=${{secrets.TEST_SECRET}} --surge_url=${{secrets.SURGE_URL}} --application_id=${{ secrets.REDDIT_APPLICATION_ID}} --application_secret=${{ secrets.REDDIT_APPLICATION_SECRET}}
      - name: Build
        run: npm run build:ci
      - name: Replace files and deploy to surge
        run: | 
          cd dist
          python deploy.py
          sudo npm install -g surge
          surge ./ ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}