on: 
  push:
    branches:
      - main
name: Deploy
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-versions: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm run test
        run: |
          npm ci
          npm run test-headless
  deploy:
    runs-on: ubuntu-latest
    needs: test
    name: Deploying to surge
    steps:
      - uses: actions/checkout@v1
      - name: Install surge and fire deployment
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: sudo npm install -g surge
      - run: surge ./ ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}